import assert from 'node:assert/strict';
import test from 'node:test';
import { computeMapGeometry } from './geo/build-layout';
import { DISTRICT_IDS, getMapGeometry, resolveDarkness } from './geography';
import placesFile from '../data/places.json';
import overrides from './geo/settlements.overrides.json';

// A lamp needs a kind, a clock and a source to say anything in the popover.
// `areas` decides which lamp it is — unless `scope` is 'district', when
// `district` does.
const outage = (areas: string[], over: Partial<Parameters<typeof resolveDarkness>[0][number]> = {}) => ({
  kind: 'planned' as const,
  startsAt: '2026-08-27T06:00:00.000Z',
  endsAt: '2026-08-27T12:00:00.000Z',
  sources: [{ name: 'Yenidüzen', url: 'https://example.invalid', kind: 'press' as const }],
  confidence: 'high' as const,
  district: 'lefkosa' as const,
  scope: 'places' as const,
  areas,
  ...over,
});

// The map the app serves is a file, generated by `npm run build:map`. This is
// the guard that it still matches the GeoJSON and the style constants it was
// generated from: edit either and this fails until the layout is rebuilt.
test('map-layout.json is in step with the data it came from', () => {
  assert.deepEqual(getMapGeometry(), computeMapGeometry());
});

test('every district is present, with a path and an area', () => {
  const { districts, width, height } = getMapGeometry();
  assert.deepEqual(
    districts.map((d) => d.id).sort(),
    [...DISTRICT_IDS].sort(),
  );
  for (const d of districts) {
    assert.ok(d.path.startsWith('M'), `${d.id} has no path`);
    assert.ok(d.area > 0, `${d.id} has no area to stack its hit target by`);
  }
  assert.equal(getMapGeometry().viewBox, `0 0 ${width} ${height}`);
});

test('settlements are projected inside the frame, west to east', () => {
  const { settlements, width, height } = getMapGeometry();
  let previous = -Infinity;
  for (const s of settlements) {
    assert.ok(s.x >= 0 && s.x <= width, `${s.name} is outside the frame`);
    assert.ok(s.y >= 0 && s.y <= height, `${s.name} is outside the frame`);
    assert.ok(s.x >= previous, `${s.name} breaks the west-to-east order`);
    previous = s.x;
  }
});

// The map is lit place by place and nothing else, so a name the ingest can
// match but the map cannot place is an outage with nowhere to show. The two
// that have no defensible coordinate are declared by hand; anything else
// drifting out of step means `npm run harvest:coords` needs re-running.
test('every place the ingest can match has a lamp, bar the declared exceptions', () => {
  const placed = new Set(getMapGeometry().settlements.map((s) => s.name));
  const declared = new Set(overrides.unplaceable.map((o) => o.name));
  const orphans = placesFile.places.map((p) => p.name).filter((n) => !placed.has(n) && !declared.has(n));
  assert.deepEqual(orphans, [], 'places.json has names settlements.json cannot place');
  for (const name of declared) {
    assert.ok(!placed.has(name), `${name} is declared unplaceable but has a lamp`);
  }
});

test('a named area darkens only itself; its neighbours stay lit', () => {
  const dark = resolveDarkness([outage(['Gönyeli', 'Hamitköy'])]);
  assert.deepEqual([...dark.keys()].sort(), ['Gönyeli', 'Hamitköy']);
  assert.ok(!dark.has('Lefkoşa'));
  assert.ok(!dark.has('Değirmenlik'));
});

test('an area named with different diacritics still matches its settlement', () => {
  const dark = resolveDarkness([outage(['YENIBOGAZICI'])]);
  assert.deepEqual([...dark.keys()], ['Yeniboğaziçi']);
});

test('a lamp that goes out carries what the popover has to say', () => {
  const dark = resolveDarkness([
    outage(['Lapta'], { kind: 'fault', endsAt: null, district: 'girne' }),
  ]);
  assert.deepEqual(dark.get('Lapta'), {
    kind: 'fault',
    startsAt: '2026-08-27T06:00:00.000Z',
    endsAt: null,
    source: 'Yenidüzen',
    confidence: 'high',
  });
});

// Nothing is invented to fill the gap. A district is shaded only where the
// announcement itself said so — `scope`, below — never as a guess made from a
// place name, which is what once said a village was out when its neighbour was.
test('an outage naming nothing we can place darkens nothing', () => {
  assert.equal(resolveDarkness([outage(['Bilinmeyen Mahalle'])]).size, 0);
});

test('where two outages name one place, the one that started first wins', () => {
  const dark = resolveDarkness([
    outage(['Girne'], { startsAt: '2026-08-27T09:00:00.000Z' }),
    outage(['Girne'], { kind: 'fault', startsAt: '2026-08-27T04:00:00.000Z' }),
  ]);
  assert.equal(dark.get('Girne')?.kind, 'fault');
});

// Every district name is also a settlement name, so 'Lefke' alone cannot say
// whether one lamp or nineteen have gone out. `scope` is the announcement's own
// answer, and this is the whole of what it buys.
test('a district-scope record darkens every settlement in its district', () => {
  const settlements = getMapGeometry().settlements;
  const inLefke = settlements.filter((s) => s.district === 'lefke');
  const dark = resolveDarkness([outage(['Lefke'], { district: 'lefke', scope: 'district' })]);
  // Counted off the layout rather than written down: the map is generated, and
  // a hardcoded number would go stale the first time a place is added.
  assert.equal(dark.size, inLefke.length);
  for (const s of inLefke) assert.ok(dark.has(s.name), `${s.name} stayed lit`);
});

test('a district-scope record darkens nothing outside its own district', () => {
  const dark = resolveDarkness([outage(['Lefke'], { district: 'lefke', scope: 'district' })]);
  assert.ok(!dark.has('Lapta'));
  assert.ok(!dark.has('Gönyeli'));
});

// The reason the two are resolved in separate passes. A district-wide record
// reaches a village by our widening; a record that names the village is evidence
// about it, and the popover has to print the clock and the source that were
// actually written about that place.
test('a record naming a place beats a district-wide one that started earlier', () => {
  const dark = resolveDarkness([
    outage(['Lefke'], {
      district: 'lefke',
      scope: 'district',
      kind: 'fault',
      endsAt: null,
      startsAt: '2026-08-27T04:00:00.000Z',
      sources: [{ name: 'Kıbrıs Postası', url: 'https://example.invalid', kind: 'press' }],
    }),
    outage(['Gemikonağı'], { district: 'lefke', startsAt: '2026-08-27T09:00:00.000Z' }),
  ]);
  const named = dark.get('Gemikonağı');
  assert.equal(named?.kind, 'planned');
  assert.equal(named?.startsAt, '2026-08-27T09:00:00.000Z');
  assert.equal(named?.source, 'Yenidüzen');
  // Every other village in the district still has the wide record.
  assert.equal(dark.get('Yeşilyurt')?.kind, 'fault');
});

test('between two district-scope records the earlier one still wins', () => {
  const dark = resolveDarkness([
    outage(['Lefke'], { district: 'lefke', scope: 'district', startsAt: '2026-08-27T09:00:00.000Z' }),
    outage(['Lefke'], {
      district: 'lefke',
      scope: 'district',
      kind: 'fault',
      startsAt: '2026-08-27T04:00:00.000Z',
    }),
  ]);
  assert.equal(dark.get('Yeşilyurt')?.kind, 'fault');
});
