import assert from 'node:assert/strict';
import test from 'node:test';
import { computeMapGeometry } from './geo/build-layout';
import { DISTRICT_IDS, getMapGeometry, resolveDarkness } from './geography';
import placesFile from '../data/places.json';
import overrides from './geo/settlements.overrides.json';

// A lamp needs a kind, a clock and a source to say anything in the popover;
// only `areas` decides which lamp it is.
const outage = (areas: string[], over: Partial<Parameters<typeof resolveDarkness>[0][number]> = {}) => ({
  kind: 'planned' as const,
  startsAt: '2026-08-27T06:00:00.000Z',
  endsAt: '2026-08-27T12:00:00.000Z',
  sources: [{ name: 'Yenidüzen', url: 'https://example.invalid', kind: 'press' as const }],
  confidence: 'high' as const,
  areas,
  ...over,
});

// The map the app serves is a file, generated by `npm run build:map`. This is
// the guard that it still matches the GeoJSON and the style constants it was
// generated from: edit either and this fails until the layout is rebuilt.
test('map-layout.json is in step with the data it came from', () => {
  assert.deepEqual(getMapGeometry(), computeMapGeometry());
});

test('every district is present, with a path and an area', () => {
  const { districts, width, height } = getMapGeometry();
  assert.deepEqual(
    districts.map((d) => d.id).sort(),
    [...DISTRICT_IDS].sort(),
  );
  for (const d of districts) {
    assert.ok(d.path.startsWith('M'), `${d.id} has no path`);
    assert.ok(d.area > 0, `${d.id} has no area to stack its hit target by`);
  }
  assert.equal(getMapGeometry().viewBox, `0 0 ${width} ${height}`);
});

test('settlements are projected inside the frame, west to east', () => {
  const { settlements, width, height } = getMapGeometry();
  let previous = -Infinity;
  for (const s of settlements) {
    assert.ok(s.x >= 0 && s.x <= width, `${s.name} is outside the frame`);
    assert.ok(s.y >= 0 && s.y <= height, `${s.name} is outside the frame`);
    assert.ok(s.x >= previous, `${s.name} breaks the west-to-east order`);
    previous = s.x;
  }
});

// The map is lit place by place and nothing else, so a name the ingest can
// match but the map cannot place is an outage with nowhere to show. The two
// that have no defensible coordinate are declared by hand; anything else
// drifting out of step means `npm run harvest:coords` needs re-running.
test('every place the ingest can match has a lamp, bar the declared exceptions', () => {
  const placed = new Set(getMapGeometry().settlements.map((s) => s.name));
  const declared = new Set(overrides.unplaceable.map((o) => o.name));
  const orphans = placesFile.places.map((p) => p.name).filter((n) => !placed.has(n) && !declared.has(n));
  assert.deepEqual(orphans, [], 'places.json has names settlements.json cannot place');
  for (const name of declared) {
    assert.ok(!placed.has(name), `${name} is declared unplaceable but has a lamp`);
  }
});

test('a named area darkens only itself; its neighbours stay lit', () => {
  const dark = resolveDarkness([outage(['Gönyeli', 'Hamitköy'])]);
  assert.deepEqual([...dark.keys()].sort(), ['Gönyeli', 'Hamitköy']);
  assert.ok(!dark.has('Lefkoşa'));
  assert.ok(!dark.has('Değirmenlik'));
});

test('an area named with different diacritics still matches its settlement', () => {
  const dark = resolveDarkness([outage(['YENIBOGAZICI'])]);
  assert.deepEqual([...dark.keys()], ['Yeniboğaziçi']);
});

test('a lamp that goes out carries what the popover has to say', () => {
  const dark = resolveDarkness([outage(['Lapta'], { kind: 'fault', endsAt: null })]);
  assert.deepEqual(dark.get('Lapta'), {
    kind: 'fault',
    startsAt: '2026-08-27T06:00:00.000Z',
    endsAt: null,
    source: 'Yenidüzen',
    confidence: 'high',
  });
});

// Nothing is invented to fill the gap: a district is not a place, and shading
// the whole of one said a village was out when only its neighbour was.
test('an outage naming nothing we can place darkens nothing', () => {
  assert.equal(resolveDarkness([outage(['Bilinmeyen Mahalle'])]).size, 0);
});

test('where two outages name one place, the one that started first wins', () => {
  const dark = resolveDarkness([
    outage(['Girne'], { startsAt: '2026-08-27T09:00:00.000Z' }),
    outage(['Girne'], { kind: 'fault', startsAt: '2026-08-27T04:00:00.000Z' }),
  ]);
  assert.equal(dark.get('Girne')?.kind, 'fault');
});
